name: demo-env-secret

on:
  workflow_dispatch:

env:
  DEPLOY_ENV: production

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ env.DEPLOY_ENV }}
      url: https://example.com

    steps:
      - name: Print environment name
        run: echo "Environment is: $DEPLOY_ENV"

      - name: Use PROD_API_KEY
        run: echo "Prod API key is: ${{ secrets.PROD_API_KEY }}"
