name: env-secret

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production   # <- links this job to the environment
    steps:
      - name: Use environment secret
        run: |
          echo "Deploying with production DB password"
          echo "Masked value: $PROD_API_KEY "
        env:
          PROD_DB_PASSWORD: ${{ secrets.PROD_API_KEY  }}
